-- GymTrainer Database Schema
-- PostgreSQL 16 — Azure PostgreSQL Flexible Server

-- User profile & training preferences
CREATE TABLE profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    display_name VARCHAR(100),
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255),
    training_goals JSONB,                         -- ["hypertrophy", "strength"]
    experience_level VARCHAR(20),                 -- beginner, intermediate, advanced
    available_days INT,
    preferred_unit VARCHAR(5) DEFAULT 'kg',       -- kg or lbs
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Weekly workout plans generated by AI
CREATE TABLE workout_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES profiles(id),
    week_start DATE NOT NULL,
    plan_json JSONB NOT NULL,                     -- Full structured plan from Claude
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Individual scheduled workout sessions
CREATE TABLE workout_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES profiles(id),
    plan_id UUID REFERENCES workout_plans(id),
    scheduled_date DATE NOT NULL,
    title VARCHAR(100) NOT NULL,
    status VARCHAR(20) DEFAULT 'scheduled',       -- scheduled, in_progress, completed, skipped
    exercises JSONB NOT NULL,                      -- exercises with YouTube URLs
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Individual sets logged during workout (progressive overload data)
CREATE TABLE exercise_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES profiles(id),
    session_id UUID REFERENCES workout_sessions(id),
    exercise_name VARCHAR(100) NOT NULL,
    set_number INT NOT NULL,
    weight_kg DECIMAL(5,1),
    reps INT NOT NULL,
    rpe DECIMAL(3,1),
    notes VARCHAR(500),
    logged_at TIMESTAMPTZ DEFAULT NOW()
);

-- Chat history with the AI agent
CREATE TABLE chat_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES profiles(id),
    role VARCHAR(20) NOT NULL,                    -- 'user' or 'assistant'
    content TEXT NOT NULL,
    tool_calls JSONB,                             -- if Claude used tools
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_exercise_logs_lookup ON exercise_logs(user_id, exercise_name, logged_at);
CREATE INDEX idx_sessions_schedule ON workout_sessions(user_id, scheduled_date);
CREATE INDEX idx_chat_history ON chat_messages(user_id, created_at);
